### PR TITLE
Package resource run in unified mode

### PR DESCRIPTION
**Pull request by bmhughes**
# Description

- Remove package exclusion logic from ruby_block - [@bmhughes](https://github.com/bmhughes)
- Package resource run in unified mode - [@bmhughes](https://github.com/bmhughes)
- Add CentOS 8 stream to kitchen testing - [@bmhughes](https://github.com/bmhughes)

## Issues Resolved

n/a

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by Xorima** [comment]
Is the minimum version of chef on for unified mode?

**Comment by bmhughes** [comment]
> 
> 
> Is the minimum version of chef on for unified mode?

Good point, it is now

**Comment by bmhughes** [comment]
Hmm i'm thinking that a Chef version requirement change merits a major release?

**Comment by Xorima** [comment]
yep, needs a major as it is a breaking change if you are on an older version

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [2.0.0](https://github.com/sous-chefs/syslog_ng/releases/tag/2.0.0)

**Pull request merged**
